apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rkc-eks-demo
  region: us-east-1

vpc:
  id: vpc-03658391eefc02dca
  subnets:
    private:
      rkc-vpc1-PrivateSubnet02: { id: subnet-0449cffda2ef34267 }
      rkc-vpc1-PrivateSubnet01: { id: subnet-0c00fdafe7abe1a0c }
    public:
      rkc-vpc1-PublicSubnet02: { id: subnet-018ad04e06ec73083 }
      rkc-vpc1-PublicSubnet01: { id: subnet-0aa7597ea560399d1 }

iam:
  serviceRoleARN: arn:aws:iam::569177097303:role/rkc-EKS-cluster-Role

managedNodeGroups:
  - name: eks-ng-1
    amiFamily: Ubuntu2004
    instanceType: t2.micro
    minSize: 1
    desiredCapacity: 1
    maxSize: 2
    volumeSize: 20
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      publicKeyPath: /eks/keys/id_rsa.pub
