apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    env: rkc-EKS-Democlusterfromec2
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    env: rkc-EKS-Democlusterfromec2
