apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    env: rkc-EKS-Democlusterfromec2
spec:
  replicas: 3
  selector:
    matchLabels:
      env: rkc-EKS-Democlusterfromec2
  template:
    metadata:
      labels:
        env: rkc-EKS-Democlusterfromec2
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
